routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//  dd('ok');
//     return view('welcome');
// });
// Route::group(['middleware' => ['web']], function () {
        // Route::get('/', 'HomeController@index');

        /*
         * Front end
         */

        // Route::match(['get', 'post'], 'home', 'Front\CartController@productList');
        // VisitStats::routes();
        Route::get('pricing', 'Front\CartController@cart')->name('pricing');
        Route::get('group/{templateid}/{groupid}/', 'Front\PageController@pageTemplates');
        Route::get('cart/remove', 'Front\CartController@cartRemove');
        Route::get('update-agent-qty', 'Front\CartController@updateAgentQty');
        Route::get('update-qty', 'Front\CartController@updateProductQty');
        Route::get('reduce-product-qty', 'Front\CartController@reduceProductQty');
        Route::get('reduce-agent-qty', 'Front\CartController@reduceAgentQty');
        Route::get('cart/clear', 'Front\CartController@clearCart');
        Route::get('show/cart', 'Front\CartController@showCart');

        Route::get('checkout', 'Front\CheckoutController@checkoutForm');
        //Route::get('checkout', 'Front\CheckoutController@CheckoutForm');
        Route::match(['post', 'patch'], 'checkout', 'Front\CheckoutController@postCheckout');

        Route::get('ping', 'Front\CheckoutController@PingRecieve');
        Route::post('pricing/update', 'Front\CartController@addCouponUpdate');
        //Route::get('mail-chimp','Common\MailChimpController@getList');
        Route::get('mail-chimp/subcribe', 'Common\MailChimpController@addSubscriberByClientPanel');
        Route::get('mail-chimp/merge-fields', 'Common\MailChimpController@addFieldsToAgora');
        Route::get('mail-chimp/add-lists', 'Common\MailChimpController@addListsToAgora');
        Route::get('mailchimp', 'Common\MailChimpController@mailChimpSettings');
        Route::patch('mailchimp', 'Common\MailChimpController@postMailChimpSettings');
        Route::get('mail-chimp/mapping', 'Common\MailChimpController@mapField');
        Route::patch('mail-chimp/mapping', 'Common\MailChimpController@postMapField');
        Route::patch('mailchimp-ispaid/mapping', 'Common\MailChimpController@postIsPaidMapField');
        Route::patch('mailchimp-group/mapping', 'Common\MailChimpController@postGroupMapField');
        Route::get('get-group-field/{value}', 'Common\MailChimpController@addInterestFieldsToAgora');
        Route::get('contact-us', 'Front\CartController@contactUs');
        Route::post('contact-us', 'Front\CartController@postContactUs');

        /*
         * Front Client Pages
         */

        Route::get('my-invoices', 'Front\ClientController@invoices')->name('my-invoices');

        Route::get('get-my-invoices', 'Front\ClientController@getInvoices')->name('get-my-invoices');
        Route::get('get-my-invoices/{orderid}/{userid}', 'Front\ClientController@getInvoicesByOrderId');

        // Route::get('get-my-invoices/{orderid}/{userid}', ['uses' => 'Front\ClientController@getInvoicesByOrderId', 'as' => 'get-my-invoices']);

        Route::get('get-my-payment/{orderid}/{userid}', ['uses' => 'Front\ClientController@getPaymentByOrderId', 'as' => 'get-my-payment']);

        // Route::get('get-my-payment/{orderid}/{userid}', 'Front\ClientController@getPaymentByOrderId');
        // Route::get('get-my-payment-client/{orderid}/{userid}', 'Front\ClientController@getPaymentByOrderIdClient');

        Route::get('get-my-payment-client/{orderid}/{userid}', ['uses' => 'Front\ClientController@getPaymentByOrderIdClient', 'as' => 'get-my-payment-client']);

        Route::get('my-orders', 'Front\ClientController@orders');
        Route::get('get-my-orders', 'Front\ClientController@getOrders')->name('get-my-orders');
        Route::get('my-subscriptions', 'Front\ClientController@subscriptions');
        Route::get('get-my-subscriptions', 'Front\ClientController@getSubscriptions');
        Route::get('my-invoice/{id}', 'Front\ClientController@getInvoice');
        Route::get('my-order/{id}', 'Front\ClientController@getOrder');
        Route::get('my-subscription/{id}', 'Front\ClientController@getSubscription');
        Route::get('my-profile', 'Front\ClientController@profile');
        Route::patch('my-profile', 'Front\ClientController@postProfile');
        Route::patch('my-password', 'Front\ClientController@postPassword');
        Route::get('paynow/{id}', 'Front\CheckoutController@payNow');

        Route::get('get-versions/{productid}/{clientid}/{invoiceid}/', ['as' => 'get-versions', 'uses' => 'Front\ClientController@getVersionList']);
        Route::get('get-github-versions/{productid}/{clientid}/{invoiceid}/', ['as' => 'get-github-versions', 'uses' => 'Front\ClientController@getGithubVersionList']);

        // Get Route For Show Razorpay Payment Form
        Route::get('paywithrazorpay', 'RazorpayController@payWithRazorpay')->name('paywithrazorpay');
        // Post Route For Make Razorpay Payment Request
        Route::post('payment/{invoice}', 'RazorpayController@payment')->name('payment');

        /*
         * Social Media
         */

        Route::resource('social-media', 'Common\SocialMediaController');
        Route::get('get-social-media', ['as' => 'get-social-media', 'uses' => 'Common\SocialMediaController@getSocials']);
        // Route::get('get-social-media', 'Common\SocialMediaController@getSocials');
        Route::get('social-media-delete', 'Common\SocialMediaController@destroy');
        /*
         * Tweeter api
         */
        Route::get('twitter', 'Common\SocialMediaController@getTweets')->name('twitter');

        /*
         * Authentication
         */
    //     Route::get([
    // // 'auth'     => 'Auth\AuthController',
    // // 'password' => 'Auth\PasswordController',
    //     ]);
        Route::auth();
        Route::get('/', 'DashboardController@index');
        Route::get('resend/activation/{email}', 'Auth\AuthController@sendActivationByGet');

        Route::get('activate/{token}', 'Auth\AuthController@activate');

         Route::get('change/email', 'Auth\AuthController@updateUserEmail');

        /*
         * Profile Process
         */

        Route::get('profile', 'User\ProfileController@profile');
        Route::patch('profile', 'User\ProfileController@updateProfile');
        Route::patch('password', 'User\ProfileController@updatePassword');

        /*
         * Settings
         */
        Route::get('settings', 'Common\SettingsController@settings');
        Route::get('settings/system', 'Common\SettingsController@settingsSystem');
        Route::patch('settings/system', 'Common\SettingsController@postSettingsSystem');
        Route::get('settings/email', 'Common\SettingsController@settingsEmail');
        Route::patch('settings/email', 'Common\SettingsController@postSettingsEmail');
        Route::get('settings/template', 'Common\SettingsController@settingsTemplate');
        Route::patch('settings/template', 'Common\SettingsController@postSettingsTemplate');
        // Route::get('settings/error', 'Common\SettingsController@settingsError');
        // Route::get('/log-viewer', 'Common\SettingsController@viewLogs');
        Route::patch('settings/error', 'Common\SettingsController@postSettingsError');
        Route::get('settings/activitylog', 'Common\SettingsController@settingsActivity');
         Route::get('settings/maillog', 'Common\SettingsController@settingsMail');
         Route::get('get-activity', ['as' => 'get-activity', 'uses' => 'Common\SettingsController@getActivity']);
          Route::get('get-email', ['as' => 'get-email', 'uses' => 'Common\SettingsController@getMails']);
         Route::get('activity-delete', 'Common\SettingsController@destroy')->name('activity-delete');
          Route::get('email-delete', 'Common\SettingsController@destroyEmail')->name('email-delete');
           Route::get('licenseDetails', 'Common\BaseSettingsController@licenseDetails')->name('licenseDetails');
            Route::get('updateDetails', 'Common\BaseSettingsController@updateDetails')->name('updateDetails');
            Route::get('captchaDetails', 'Common\BaseSettingsController@captchaDetails')->name('captchaDetails');
            Route::get('updatemobileDetails', 'Common\BaseSettingsController@updateMobileDetails')->name('updatemobileDetails');
            Route::get('updateemailDetails', 'Common\BaseSettingsController@updateEmailDetails')->name('updateemailDetails');
            Route::get('updatetwitterDetails', 'Common\BaseSettingsController@updateTwitterDetails')->name('updatetwitterDetails');
            Route::get('updateMailchimpDetails', 'Common\BaseSettingsController@updateMailchimpDetails')->name('updateMailchimpDetails');
             Route::get('updateTermsDetails', 'Common\BaseSettingsController@updateTermsDetails')->name('updateTermsDetails');
            Route::get('updaterzpDetails', 'Common\BaseSettingsController@updateRazorpayDetails')->name('updaterzpDetails');
             Route::get('updatezohoDetails', 'Common\BaseSettingsController@updateZohoDetails')->name('updatezohoDetails');
             Route::get('updatepipedriveDetails', 'Common\BaseSettingsController@updatepipedriveDetails')->name('updatepipedriveDetails');
              Route::get('mailchimp-prod-status', 'Common\BaseSettingsController@updateMailchimpProductStatus')->name('mailchimp-prod-status');
               Route::get('mailchimp-paid-status', 'Common\BaseSettingsController@updateMailchimpIsPaidStatus')->name('mailchimp-paid-status');

app/Http/Controllers/Product/ExtendedPlanController.php
<?php

namespace App\Http\Controllers\Product;

use App\Http\Controllers\Controller;
use App\Model\Payment\Period;
use Illuminate\Http\Request;

/////
//Handles Operations for Setting up Product Plans //
/////
class ExtendedPlanController extends Controller
{
    /**
     * Insert Period Into Database.
     *
     * @author Ashutosh Pathak <ashutosh.pathak@ladybirdweb.com>
     *
     * @date   2019-01-08T02:27:37+0530
     *
     * @param Request $request Get Name And Days as Parameter
     *
     * @return json Suucess or Failure
     */
    public function postInsertPeriod(Request $request)
    {
        $this->validate($request, [
        'name' => 'required',
        'days' => 'required|numeric',
        ]);

        try {
            if ($request->ajax()) {
                return response(Period::create($request->all()));
            }
        } catch (\Exception $ex) {
            $result = [$ex->getMessage()];

            return response()->json(compact('result'), 500);
        }
    }
}

app/Http/Controllers/Product/ProductTypeController.php
<?php

namespace App\Http\Controllers\Product;

use App\Http\Controllers\Controller;
use App\Model\Product\ProductType;
use Bugsnag;
use Illuminate\Http\Request;

class ProductTypeController extends Controller
{
    public $productType;

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin');

        $productType = new ProductType();
        $this->productType = $productType;
    }

    public function index()
    {
        return view('themes.default1.product.type.index');
    }

    /*
    * Get All the categories
    */
    public function getTypes()
    {
        try {
            $allTypes = $this->productType->select('id', 'name')->get();

            return \DataTables::of($allTypes)
         ->addColumn('checkbox', function ($model) {
             return "<input type='checkbox' class='type_checkbox' 
            value=".$model->id.' name=select[] id=check>';
         })
         ->addColumn('type_name', function ($model) {
             return ucfirst($model->name);
         })
         ->addColumn('action', function ($model) {
             return "<p><button data-toggle='modal' 
             data-id=".$model->id." data-name= '$model->name' 
             class='btn btn-sm btn-primary btn-xs editType'><i class='fa fa-edit'
             style='color:white;'> </i>&nbsp;&nbsp;Edit</button>&nbsp;</p>";
         })
         ->rawColumns(['checkbox', 'type_name', 'action'])
         ->make(true);
        } catch (\Exception $ex) {
            Bugsnag::notifyException($ex);

            return redirect()->back()->with('fails', $ex->getMessage());
        }
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $productType = $this->productType->fill($request->input())->save();

            return redirect()->back()->with('success', \Lang::get('message.saved-successfully'));
        } catch (\Exception $ex) {
            return redirect()->back()->with('fails', $ex->getMessage());
        }
    }

    public function update(Request $request, $id)
    {
        try {
            $type_name = $request->input('name');
            $type = $this->productType->where('id', $id)->update(['name' =>$type_name]);

            return redirect()->back()->with('success', \Lang::get('message.updated-successfully'));
        } catch (\Exception $ex) {
            Bugsnag::notifyException($ex);

            return redirect()->back()->with('fails', $ex->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        try {
            $ids = $request->input('select');
            if (!empty($ids)) {
                foreach ($ids as $id) {
                    if ($id != 1) {
                        $type = $this->productType->where('id', $id)->first();
                        if ($type) {
                            $type->delete();
                        } else {
                            echo "<div class='alert alert-danger alert-dismissable'>
                    <i class='fa fa-ban'></i>
                    <b>"./* @scrutinizer ignore-type */\Lang::get('message.alert').'!</b> '.
                    /* @scrutinizer ignore-type */\Lang::get('message.failed').'
                    <button type=button class=close data-dismiss=alert aria-hidden=true>&times;</button>
                        './* @scrutinizer ignore-type */\Lang::get('message.no-record').'
                </div>';
                            //echo \Lang::get('message.no-record') . '  [id=>' . $id . ']';
                        }
                        echo "<div class='alert alert-success alert-dismissable'>
                    <i class='fa fa-ban'></i>

                    <b>"./* @scrutinizer ignore-type */\Lang::get('message.alert').'!</b> '.
                    /* @scrutinizer ignore-type */\Lang::get('message.success').'

                    <button type=button class=close data-dismiss=alert aria-hidden=true>&times;</button>
                        './* @scrutinizer ignore-type */\Lang::get('message.deleted-successfully').'
                </div>';
                    } else {
                        echo "<div class='alert alert-danger alert-dismissable'>
                    <i class='fa fa-ban'></i>
                    <b>"./* @scrutinizer ignore-type */\Lang::get('message.alert').'!</b> '.
                    /* @scrutinizer ignore-type */\Lang::get('message.failed').'
                    <button type=button class=close data-dismiss=alert aria-hidden=true>&times;</button>
                        './* @scrutinizer ignore-type */\Lang::get('message.can-not-delete-default').'
                </div>';
                    }
                }
            } else {
                echo "<div class='alert alert-danger alert-dismissable'>
                    <i class='fa fa-ban'></i>
                    <b>"./* @scrutinizer ignore-type */\Lang::get('message.alert').'!</b> '.
                    /* @scrutinizer ignore-type */\Lang::get('message.failed').'
                    <button type=button class=close data-dismiss=alert aria-hidden=true>&times;</button>
                        './* @scrutinizer ignore-type */\Lang::get('message.select-a-row').'
                </div>';
                //echo \Lang::get('message.select-a-row');
            }
        } catch (\Exception $e) {
            echo "<div class='alert alert-danger alert-dismissable'>
                    <i class='fa fa-ban'></i>
                    <b>"./* @scrutinizer ignore-type */\Lang::get('message.alert').'!</b> '.
                    /* @scrutinizer ignore-type */
                    \Lang::get('message.failed').'
                    <button type=button class=close data-dismiss=alert aria-hidden=true>&times;</button>
                        '.$e->getMessage().'
                </div>';
        }
    }
}

resources/views/themes/default1/product/type/create-type.blade.php
 <div class="modal fade" id="create-type">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">{{Lang::get('message.create-type')}}</h4>
            </div>
            {!! Form::open(['url'=>'product-type']) !!} 
            <div class="modal-body">
                
                <div class= "form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    {!! Form::label('name',Lang::get('message.type-name'),['class'=>'required']) !!}
                    <input type="text" name="name" class="form-control" required="required">
                </div>
            </div>
            <div class="modal-footer">
                 <button type="button" id="close" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary " id="submit" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'>&nbsp;</i> Saving..."><i class="fa fa-floppy-o">&nbsp;&nbsp;</i>{!!Lang::get('Save')!!}</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/themes/default1/product/type/edit-type.blade.php
 <div class="modal fade" id="edit-type">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">{{Lang::get('message.edit-type')}}</h4>
            </div>
           {!! Form::open(['method' => 'patch', 'id' =>  'type-edit-form'])!!}
            <div class="modal-body">
                
                <div class= "form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    {!! Form::label('name',Lang::get('message.category-name'),['class'=>'required']) !!}
                    <input type="text" name="name" id="tname" class="form-control" required="required">
                </div>
            </div>
            <div class="modal-footer">
                 <button type="button" id="close" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary " id="submit" data-loading-text="<i class='fa fa-circle-o-notch fa-spin'>&nbsp;</i> Saving..."><i class="fa fa-refresh">&nbsp;&nbsp;</i>{!!Lang::get('message.update')!!}</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/themes/default1/product/type/index.blade.php
@extends('themes.default1.layouts.master')
@section('title')
Product Types
@stop
@section('content-header')
<h1>
Product Types
</h1>
  <ol class="breadcrumb">
        <li><a href="{{url('/')}}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">All Types</li>
      </ol>
@stop
@section('content')

    <div class="box box-primary">

    <div class="box-header">
        @if (count($errors) > 0)
        <div class="alert alert-danger alert-dismissable">
             <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif

        @if(Session::has('success'))
        <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
             <b>{{Lang::get('message.success')}}!</b>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{Session::get('success')}}
        </div>
        @endif
        <!-- fail message -->
        @if(Session::has('fails'))
        <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <b>{{Lang::get('message.alert')}}!</b> {{Lang::get('message.failed')}}.
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{Session::get('fails')}}
        </div>
        @endif
        <div id="response"></div>
        <h4>{{Lang::get('message.types')}}
            <a href="#create-type" data-toggle="modal" data-target="#create-type" class="btn btn-primary btn-sm pull-right"><span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;{{Lang::get('message.create')}}</a></h4>
    </div>
       @include('themes.default1.product.type.create-type')
        @include('themes.default1.product.type.edit-type')
       <div class="box-body">
             
             <div class="row">
            
            <div class="col-md-12">
               
                 <table id="products-table" class="table display" cellspacing="0" width="100%" styleClass="borderless">
                     <button  value="" class="btn btn-danger btn-sm btn-alldell" id="bulk_delete"><i class="fa fa-trash"></i>&nbsp;&nbsp;{{Lang::get('message.delmultiple')}}</button><br /><br />
                    <thead><tr>
                        <th class="no-sort" style="width:20px"><input type="checkbox" name="select_all" onchange="checking(this)"></th>
                            <th>Name</th>
                            <th>Action</th>
                        </tr></thead>

                   </table>
            </div>
        </div>

    </div>

</div>

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" />
<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
        $('#products-table').DataTable({
            processing: true,
            serverSide: true,
             stateSave: false,
              order: [[ 0, "desc" ]],
            ajax: '{!! route('get-type') !!}',
            "oLanguage": {
                "sLengthMenu": "_MENU_ Records per page",
                "sSearch"    : "Search: ",
                "sProcessing": '<img id="blur-bg" class="backgroundfadein" style="top:40%;left:50%; width: 50px; height:50 px; display: block; position:    fixed;" src="{!! asset("lb-faveo/media/images/gifloader3.gif") !!}">'
            },
            columnDefs: [
                { 
                    targets: 'no-sort', 
                    orderable: false,
                    order: []
                }
            ],
            columns: [
                {data: 'checkbox', name: 'checkbox'},
                {data: 'type_name', name: 'type_name'},
                {data: 'action', name: 'action'}
            ],
            "fnDrawCallback": function( oSettings ) {
                bindEditButton();
                $('.loader').css('display', 'none');
            },
            "fnPreDrawCallback": function(oSettings, json) {
                $('.loader').css('display', 'block');
            },
        });
    </script>
 <script>
    function checking(e){
      $('#products-table').find("td input[type='checkbox']").prop('checked',$(e).prop('checked'));
    }


    function bindEditButton() {
        $('.editType').click(function(){
           var typeName = $(this).attr('data-name');
           var typeId   = $(this).attr('data-id');
            $("#edit-type").modal('show');
            $('#tname').val(typeName);
             var url = "{{url('product-type/')}}"+"/"+typeId
        $("#type-edit-form").attr('action', url)
        })
    }

      $(document).on('click','#bulk_delete',function(){
      var id=[];
      if (confirm("Are you sure you want to delete this?"))
        {
            $('.type_checkbox:checked').each(function(){
              id.push($(this).val())
            });
            if(id.length >0)
            {
               $.ajax({
                      url:"{!! route('type-delete') !!}",
                      method:"get",
                      data: $('#check:checked').serialize(),
                      beforeSend: function () {
                $('#gif').show();
                },
                success: function (data) {
                $('#gif').hide();
                $('#response').html(data);
                location.reload();
                }
               })
            }
            else
            {
                alert("Please select at least one checkbox");
            }
        }  

     });
 </script>

@stop